### PR TITLE
Final merge before report is due

### PR DESCRIPTION
**Pull request by danieljaffe**
The implimentRedis branch was taken as the speed ups present there are preferred over the optimizations made in decoupleDataLoader. For grading, decoupleDataLoader should be examined too as there was a good amount of work put in there in examining if that would be a more viable option.

Still missing are GraphQL subscriptions. We are very close but given that we are using subscribeToMore instead of standard subscriptions, we haven't quite been able to get it functioning. Hopefully tonight?

### CODE REVIEW

**Review by dbreon88 — COMMENTED** [review]
fire fire fire

**Comment by dbreon88** [comment]
> The implimentRedis branch was taken as the speed ups present there are preferred over the optimizations made in decoupleDataLoader. For grading, decoupleDataLoader should be examined too as there was a good amount of work put in there in examining if that would be a more viable option.
> 
> Still missing are GraphQL subscriptions. We are very close but given that we are using subscribeToMore instead of standard subscriptions, we haven't quite been able to get it functioning. Hopefully tonight?

I would say that they are preferred for our current applications feature set though, the SQL improvements are crucial to the future of our application and new features. All described in the Paper.

**Comment by danieljaffe** [comment]
> > The implimentRedis branch was taken as the speed ups present there are preferred over the optimizations made in decoupleDataLoader. For grading, decoupleDataLoader should be examined too as there was a good amount of work put in there in examining if that would be a more viable option.
> > Still missing are GraphQL subscriptions. We are very close but given that we are using subscribeToMore instead of standard subscriptions, we haven't quite been able to get it functioning. Hopefully tonight?
> 
> I would say that they are preferred for our current applications feature set though, the SQL improvements are crucial to the future of our application and new features. All described in the Paper.

Yes agreed. Apologies, I should have specified.

**Review by aybeshlikyan — APPROVED** [review]
Looks good! Ready to merge.

**Review by danieljaffe — COMMENTED** [review]
Code reviewed-- after D man ninja merged XD

**Pull request merged**
